### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by mikemhenry** [samplchallenges/SAMPL-league#4]
MVP *really* shouldn't be part of the name, instead we can use releases to indicate the state of development.

Maybe:

`SAMPL-container-infra`

**Comment by mikemhenry** [comment]
Thoughts @robbason ?

**Comment by robbason** [comment]
How about SAMPL-league? I know it's not obviously meaningful but otherwise
the name will be very long, and it manages submissions. The most famous
'sub mission' is in Jules Verne's 20,000 leagues under the sea. :) There's
also an implication of cooperation.

Some relevant terms:
Submissions
Challenges
Containers
Reproducibility

Maybe:
Sampl-containership / cargoship / carrier
Conseil: the faithful, dedicated servant in the above mentioned book.

More obvious:
Submission-processor
Challenge-manager

Do any of these feel right to you?

**Comment by mikemhenry** [comment]
I love it! I will think about these :)

@davidlmobley might have some ideas/input as well

**Comment by davidlmobley** [comment]
Sorry for the delay on this. I like:
- SAMPL-league
- SAMPL-containers
- SAMPL-carrier
- SAMPL-manager

I think I like the "SAMPL-league" idea though. It's clever.

**Comment by mikemhenry** [comment]
+1 on `SAMPL-league`
